config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :employees
  resources :customers, only: [:index, :new, :create]
  resources :transactions, only: [:index, :new, :create]
  resources :employee_transactions, only: [:new, :create]
  resources :favorite_recipients, only: [:index, :new, :create, :destroy]

  get 'home/home'
  get 'accounts/account_details', to: 'home#account_details', as: 'account_details'
  get 'accounts/new', to: 'home#new_account', as: 'new_account'
  post 'home/approve_account_request/:id', to: 'home#approve_account_request', as: 'approve_account_request'
  
  root to: "home#home"
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_admin!, except: %i[index]
  before_action :set_user, except: %i[index new create]

  def index
    @employees = if params[:search].present?
                   User.employee.where('users.name ILIKE ?', "%#{params[:search]}%")
                 else
                   User.employee
                 end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.add_role(:employee)

    if @user.save
      UserMailer.new_employee_email(@user).deliver_now
      redirect_to employees_path, notice: 'Employee user created successfully.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to employees_path, notice: 'Employee was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to employees_path, notice: 'Employee successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= form_for(@user, url: employee_path, html: { class: "needs-validation", novalidate: true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.submit "Update Employee", class: "btn btn-primary", data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Back', employees_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<% if current_user.admin? %>
  <%= link_to 'Add Employee', new_employee_path, class: "btn btn-primary mb-3" %>
<% end %>

<%= form_tag(employees_path, method: :get) do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search by name" %>
  </div>
  <%= submit_tag "Search", class: "btn btn-primary" %>
  <%= link_to 'Back', employees_path, class: "btn btn-secondary ml-2" %>
<% end %>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Created At</th>
      <% if current_user.admin? %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.created_at.strftime("%m/%d/%Y %I:%M %p") %></td>
        <% if current_user.admin? %>
          <td>
            <%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-primary btn-sm mr-2" %>
            <%= link_to 'Delete', employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= form_for(@user, url: employees_path, html: { class: "needs-validation", novalidate: true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :password_confirmation, class: "form-label" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.submit "Create Employee", class: "btn btn-primary" %>
    <%= link_to 'Back', employees_path, class: "btn btn-secondary" %>
  </div>
<% end %>