config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :employees
  resources :customers, only: [:index, :new, :create]
  resources :transactions, only: [:index, :new, :create]
  resources :employee_transactions, only: [:new, :create]
  resources :favorite_recipients, only: [:index, :new, :create, :destroy]

  get 'home/home'
  get 'accounts/account_details', to: 'home#account_details', as: 'account_details'
  get 'accounts/new', to: 'home#new_account', as: 'new_account'
  post 'home/approve_account_request/:id', to: 'home#approve_account_request', as: 'approve_account_request'
  
  root to: "home#home"
end

app/views/shared/_sidebar.html.erb
<nav id="sidebar">
  <div class="sidebar-header">
    <h3>BMS</h3>
  </div>
  <ul class="list-unstyled components">
    <li>
      <% if current_user.present? %>
        <%= link_to 'Home' ,root_path %>
        <li>
          <% if current_user.admin? || current_user.employee? %>
            <%= link_to 'Employees', employees_path %> 
            <%= link_to 'Customers', customers_path %>
            <%= link_to "Transaction", new_employee_transaction_path %>  
          <% else %>
            <%= link_to "Account Details", account_details_path(customer_id: current_user.customer.id) %>
            <%= link_to "Favorite Receipents", favorite_recipients_path, method: :get %>
            <%= link_to "Transaction", new_transaction_path %>
            <%= link_to "Transaction History", transactions_path, method: :get %>
          <% end %>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to logout?" },class:"btn-link"%>
          </li>
        </li>
      <% else %>
        <%= link_to "Log In", new_user_session_path, method: :get, class:"btn-link"%>
        <%= link_to "Account Request", new_customer_path %>
      <% end %>
    </li>
  </ul> 
</nav>

app/views/shared/_toast.html.erb
<% if notice.present? %>
  <script type="text/javascript">
    toastr.success("<%= j(notice) %>");
  </script>
<% end %>

<% if alert.present? %>
  <script type="text/javascript">
    toastr.error("<%= j(alert) %>");
  </script>
<% end %>