config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :employees
  resources :customers, only: [:index, :new, :create]
  resources :transactions, only: [:index, :new, :create]
  resources :employee_transactions, only: [:new, :create]
  resources :favorite_recipients, only: [:index, :new, :create, :destroy]

  get 'home/home'
  get 'accounts/account_details', to: 'home#account_details', as: 'account_details'
  get 'accounts/new', to: 'home#new_account', as: 'new_account'
  post 'home/approve_account_request/:id', to: 'home#approve_account_request', as: 'approve_account_request'
  
  root to: "home#home"
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user, optional: true
  has_one :account_request, dependent: :destroy
  has_one :account
  has_many :transaction_logs
  has_many :favorite_recipients, dependent: :destroy

  validates :phone, presence: true, format: { with: /\A\d{10}\z/, message: "should be a 10-digit number" }
  validates :address, presence: true
  validate :birthdate_cannot_be_future_date
  validates :gender, presence: true

  after_create :create_account_request

  private

  def birthdate_cannot_be_future_date
    if birthdate.present? && birthdate.future?
      errors.add(:birthdate, "cannot be a future date")
    end
  end

  def create_account_request
    @account_request = AccountRequest.create(customer_id: self.id, user_id: self.employee_id, status: 'pending')
    if @account_request.save!
      AccountRequestMailer.account_request_approval(@account_request).deliver_now
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]
  before_action :authenticate_admin!, only: %i[new]
  before_action :authenticate_admin_employee!, only: %i[index]

  def index
    @customers = Customer.all
    if params[:status].present?
      @customers = Customer.joins(:account_requests).where(account_requests: { status: params[:status] })
    elsif params[:account_number].present?
      @customers = Customer.joins(:account).where(accounts: { account_number: params[:account_number] })
    end
  end

  def new
    @employees = User.employee
    @user = User.new
    @user.build_customer
  end

  def create
    @user = User.new(user_params)
    @user.add_role(:customer)

    if @user.save
      flash[:success] = 'Your account creation request has been submitted successfully'
      if current_user&.admin?
        redirect_to customers_path
      else
        redirect_to new_user_session_path
      end
    else
      flash[:alert] = 'Please fill the proper details'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                 customer_attributes: %i[phone address birthdate gender employee_id])
  end
end

app/views/customers/index.html.erb
<h1>Customers</h1>

<!-- Add search filter -->
<div class="row mb-3">
  <div class="col-md-6">
    <%= form_with(url: customers_path, method: :get, local: true, class: "form-inline") do |form| %>
      <div class="form-group mr-2">
        <%= form.label :status, "Search by Status:", class: "mr-2" %>
        <%= form.select :status, options_for_select([["All", ""], ["Pending", "pending"], ["Approved", "approved"]]), {}, class: "form-control" %>
      </div>
      <%= form.button "Search by Status", type: :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-6 d-flex justify-content-end">
    <%= form_with(url: customers_path, method: :get, local: true, class: "form-inline") do |form| %>
      <div class="form-group mr-2">
        <%= form.label :account_number, "Search by Account Number:", class: "mr-2" %>
        <%= form.text_field :account_number, class: "form-control" %>
      </div>
      <%= form.button "Search by Account Number", type: :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<% if current_user.admin? %>
  <%= link_to "Add Customer", new_customer_path, class: "btn btn-primary mb-3" %>
<% end %>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.user.name %></td>
        <td><%= customer.user.email %></td>
        <td><%= customer.account_request.status.capitalize %></td>
        <td>
          <% if customer.account_request.status == 'approved' %>
            <%= link_to "Account Details", account_details_path(customer_id: customer.id), class: "btn btn-primary btn-sm" %>
          <% elsif customer.account_request.status == 'pending' %>
            <%= link_to 'Create Account', new_account_path(customer_id: customer.user.id), method: :get, class: "btn btn-primary btn-sm" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<body class="bg">
	<div class="main">
		<section class="signup">
			<div class="divcontainer">
				<div class="signup-content">
					<%= form_for @user, url: customers_path do |f| %>
            <% if current_user.present? && current_user.admin? %>
              <h2 class="form-title">Create Customer Account</h2>
            <% else %>
						  <h2 class="form-title">Request Account</h2>
            <% end %>  
						<div class="form-group">
							<%= f.text_field :name, class: 'form-input' , placeholder: 'Your Name' ,required: true %>
						</div>
						<div class="form-group">
							<%= f.email_field :email, class: 'form-input' , placeholder: 'Your Email' ,required: true %>
						</div>
						<div class="form-group">
							<%= f.password_field :password, class: 'form-input' , placeholder: 'Password' %>
							<span toggle="#password" class="zmdi zmdi-eye field-icon toggle-password"></span>
						</div>
						<div class="form-group">
							<%= f.password_field :password_confirmation, class: 'form-input' , placeholder: 'Repeat your password',required: true %>
						</div>
            <%= f.fields_for :customer do |c| %>
              <div class="form-group">
                <%= c.text_field :phone, class: 'form-input', placeholder: 'Your Phone Number', required: true %>
              </div>

              <div class="form-group">
                <%= c.text_field :address, class: 'form-input', placeholder: 'Your Home Address', required: true %>
              </div>

              <div class="form-group">
                <%= c.label :birthdate, class: 'form-label' %>
                <%= c.date_field :birthdate, class: 'form-input', placeholder: 'Your Birthdate', required: true %>
              </div>

              <div class="form-group">
                <%= c.label :gender, class: 'form-label' %>
                <div class="form-radio-group">
                  <%= c.radio_button :gender, 'Male', id: 'gender_male', class: 'form-radio' %>
                  <%= c.label :gender_male, class: 'form-radio-label', for: 'gender_male' do %>
                    <span class="form-radio-text">Male</span>
                  <% end %>
              
                  <%= c.radio_button :gender, 'Female', id: 'gender_female', class: 'form-radio' %>
                  <%= c.label :gender_female, class: 'form-radio-label', for: 'gender_female' do %>
                    <span class="form-radio-text">Female</span>
                  <% end %>
              
                  <%= c.radio_button :gender, 'Other', id: 'gender_other', class: 'form-radio' %>
                  <%= c.label :gender_other, class: 'form-radio-label', for: 'gender_other' do %>
                    <span class="form-radio-text">Other</span>
                  <% end %>
                </div>
              </div>
              <% if @employees %>
                <div class="mb-3">
                  <%= c.label :employee_id, 'Select Employee', class: 'form-label' %>
                  <%= c.collection_select :employee_id, @employees, :id, :name, { prompt: 'Select Employee' }, class: 'form-select' %>
                </div>
              <% end %>             
            <% end %>
            <% if current_user.present? && current_user.admin? %>
              <div class="form-group">
                <%= f.submit 'Create Account' , name: 'submit' , id: 'submit' , class: 'form-submit' %>
              </div>
              <div class="text-center mb-3"> <!-- Add text-center class for center alignment -->
                <%= link_to 'Back', customers_path, class: "btn btn-secondary" %>
              </div>
            <% else %>
              <div class="form-group">
                <%= f.submit 'Send Request' , name: 'submit' , id: 'submit' , class: 'form-submit' %>
              </div>
              <div class="link">
                <%= link_to "Log in", new_user_session_path %><br />
              </div>
            <% end %>
          <% end %>
				</div>
			</div>
		</section>
	</div>
</body>