config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :employees
  resources :customers, only: [:index, :new, :create]
  resources :transactions, only: [:index, :new, :create]
  resources :employee_transactions, only: [:new, :create]
  resources :favorite_recipients, only: [:index, :new, :create, :destroy]

  get 'home/home'
  get 'accounts/account_details', to: 'home#account_details', as: 'account_details'
  get 'accounts/new', to: 'home#new_account', as: 'new_account'
  post 'home/approve_account_request/:id', to: 'home#approve_account_request', as: 'approve_account_request'
  
  root to: "home#home"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_employee_transaction, only: %i[new create]
  before_action :set_account, only: %i[new create]

  def index
    @transaction_logs = current_user.customer.transaction_logs.order(created_at: :desc)
  end

  def new
    @transaction_types = Transaction.transaction_types
    @transaction = @account.transactions.build
  end

  def create
    @transaction = @account.transactions.build(transaction_params)
    @transaction.starting_balance = @account.balance || 0

    case @transaction.transaction_type
    when 'deposit'
      @transaction.ending_balance = @transaction.starting_balance + @transaction.amount
    when 'withdrawal'
      handle_withdrawal
    when 'transfer'
      handle_transfer
    end

    if @transaction.save
      handle_successful_transaction
    else
      render :new
    end
  end

  private

  def update_account_balance(account, transaction)
    account.update!(balance: transaction.ending_balance || 0)
  end

  def update_employee_transaction_id(employee_transaction, transaction)
    employee_transaction.update!(transaction_id: transaction.id)
  end

  def handle_withdrawal
    if @transaction.starting_balance < @transaction.amount
      flash[:alert] = 'Insufficient balance'
      redirect_to new_transaction_path
    else
      @transaction.ending_balance = @transaction.starting_balance - @transaction.amount
    end
  end

  def handle_transfer
    recipient_account = find_recipient_account

    if recipient_account.nil?
      flash[:alert] = 'Recipient account not found'
      redirect_to new_transaction_path
    elsif @transaction.starting_balance < @transaction.amount
      flash[:alert] = 'Insufficient balance'
      redirect_to new_transaction_path
    else
      withdraw_money
      perform_transfer(recipient_account)
    end
  end

  def find_recipient_account
    if params[:transaction][:favorite_recipient_id].present?
      recipient_account_number = FavoriteRecipient.find(params[:transaction][:favorite_recipient_id]).account_number
      Account.find_by(account_number: recipient_account_number)
    else
      Account.find_by(account_number: params[:transaction][:recipient_account_number])
    end
  end

  def perform_transfer(recipient_account)
    ActiveRecord::Base.transaction do
      @transaction.save!
      create_transaction_log(@transaction)
      recipient_transaction = recipient_account.transactions.create!(
        amount: @transaction.amount,
        description: @transaction.description,
        transaction_type: 'deposit',
        starting_balance: recipient_account.balance || 0,
        ending_balance: (recipient_account.balance || 0) + @transaction.amount
      )
      create_transaction_log(recipient_transaction)

      update_account_balance(@account, @transaction)
      update_account_balance(recipient_account, recipient_transaction)
      update_employee_transaction_id(@employee_transaction, @transaction)
    end

    flash[:notice] = 'Transfer successful'
    redirect_to root_path
  end

  def handle_successful_transaction
    create_transaction_log(@transaction)
    update_account_balance(@account, @transaction)
    update_employee_transaction_id(@employee_transaction, @transaction)
    flash[:notice] = 'Transaction successful'
    redirect_to root_path
  end

  def set_employee_transaction
    @employee_transaction = EmployeeTransaction.last
  end

  def set_account
    @account = if current_user.employee? || current_user.admin?
                 Account.find_by(account_number: @employee_transaction.customer_account_number)
               else
                 current_user.customer.account
               end
  end

  def create_transaction_log(transaction)
    TransactionLog.create(
      related_transaction: transaction,
      transaction_amount: transaction.amount,
      starting_balance: transaction.starting_balance,
      ending_balance: transaction.ending_balance,
      transaction_type: transaction.transaction_type,
      customer_id: transaction.account.customer.id,
      transaction_id: transaction.id
    )
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :description, :transaction_type, :recipient_account_number)
  end
end

app/views/transactions/index.html.erb
<div class="container">
  <h1>Transaction History</h1>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Date</th>
        <th>Type</th>
        <th>Amount</th>
        <th>Starting Balance</th>
        <th>Ending Balance</th>
      </tr>
    </thead>
    <tbody>
      <% @transaction_logs.each do |transaction| %>
        <tr>
          <td><%= transaction.created_at.strftime("%m/%d/%Y %I:%M %p") %></td>
          <td><%= transaction.transaction_type.titleize %></td>
          <td><%= number_to_currency(transaction.transaction_amount, unit: "₹") %></td>
          <td><%= number_to_currency(transaction.starting_balance, unit: "₹") %></td>
          <td><%= number_to_currency(transaction.ending_balance, unit: "₹") %></td> 
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= form_with(model: @transaction, local: true, data: { remote: true }) do |form| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>
  <br/>

  <% if current_user.customer? %>
    <div class="mb-3">
      <strong>Transaction Type:</strong> Transfer
      <%= form.hidden_field :transaction_type, value: 'transfer' %>
    </div>
    <%= link_to 'Add to Favorite', new_favorite_recipient_path, class: "btn btn-primary btn-sm" %> <br/>
    <div class="mb-3">
      <%= form.label :recipient_account_number %>
      <%= form.text_field :recipient_account_number, class: "form-control" %>
    </div>

    <h4>Or select from favorite recipients:</h4>
    <%= form.collection_select :favorite_recipient_id, current_user.customer.favorite_recipients, :id, :recipient_name, { prompt: 'Select favorite recipient' }, class: 'form-select' %> <br/>

  <% else %>
    <div class="mb-3">
      <%= form.label :transaction_type, 'Transaction Type', class: 'form-label' %>
      <%= form.select :transaction_type, options_for_select(@transaction_types.keys.map {|transaction_type| [transaction_type.titleize, transaction_type]}), { prompt: 'Select transaction_type' }, class: 'form-select', required: true, id: 'transaction-type-select' %>
    </div>

    <div id="recipient-account-number-field" style="display: none;">
      <%= form.label :recipient_account_number %>
      <%= form.text_field :recipient_account_number, class: "form-control", disabled: true %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  const transactionTypeSelect = document.getElementById('transaction-type-select');
  const recipientAccountNumberField = document.getElementById('recipient-account-number-field');

  transactionTypeSelect.addEventListener('change', (event) => {
    if (event.target.value === 'transfer') {
      recipientAccountNumberField.classList.remove('d-none');
      recipientAccountNumberField.style.display = 'block';
      recipientAccountNumberField.querySelector('input').disabled = false;
    } else {
      recipientAccountNumberField.classList.add('d-none');
      recipientAccountNumberField.querySelector('input').disabled = true;
    }
  });
</script>